[deps]
{{ cookiecutter.project_name.replace('.jl', '') }} = "{{ cookiecutter.uuid }}"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[sources]
{{ cookiecutter.project_name.replace('.jl', '') }} = {path = ".."}
