# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "{{cookiecutter.project_name}}/.github/workflows/"
    schedule:
      interval: "weekly"
